version: 3
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data-latest:/data/db
    command: --wiredTigerCacheSizeGB 1.5


#version: 3
#services:
#  top.api:
#    image: top-api:latest
#    container_name: top-api
#    restart: always
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./.env:/opt/app/.env
